package jp.jaxa.iss.kibo.rpc.thailand.pathfind;

enum POI_Id {
    START, GOAL,
    POINT_1, POINT_2, POINT_3, POINT_4, POINT_5, POINT_6, POINT_7,
    TARGET_1, TARGET_2, TARGET_3, TARGET_4, TARGET_5, TARGET_6,
    QR_CODE, REALPOINT_1, REALPOINT_2, REALPOINT_3, REALPOINT_4
}
