package jp.jaxa.iss.kibo.rpc.thailand.pathfind;

enum POI_Id {
    START, GOAL,
    POINT_1, POINT_2, POINT_3, POINT_4, POINT_5, POINT_6, POINT_7,
    TARGET_1, TARGET_2, TARGET_3, TARGET_4, TARGET_5, TARGET_6,
    QR_CODE, REAL_POINT_1, REAL_POINT_2, REAL_POINT_3, REAL_POINT_4
}
